### ISSUE TITLE
có cần rating ko mọi người

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/EComBE#76]

**Comment by iamReinir** [comment]
Cái này chủ yếu code dưới BE: 
thêm bảng rating để lưu rating của từng người dùng với sản phẩm + field để lưu rating trung bình trong model của sản phẩm. Mỗi lần người dùng thêm rating là phải tính lại rating trung bình của sản phẩm.
complex.

FE chỉ hiện rating/gửi rating về BE.
simple

**Comment by iamReinir** [comment]
Để t thêm phía BE....
